# Generated by Django 3.0.6 on 2020-05-23 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_job_heykorean'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_heykorean',
            name='area',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='job_heykorean',
            name='deadline',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='job_heykorean',
            name='jobstyle',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='job_heykorean',
            name='salary',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
