# Generated by Django 3.0.6 on 2020-05-23 11:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200522_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_heykorean',
            name='fetched_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
