# Generated by Django 3.0.6 on 2020-05-23 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200523_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_heykorean',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
