# Generated by Django 3.0.6 on 2020-05-28 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_job_jobkorea'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job_jobkorea',
            old_name='eduction',
            new_name='education',
        ),
    ]
