# Generated by Django 3.0.6 on 2020-05-28 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200528_0247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_Job_Korea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('company_etc', models.CharField(max_length=200, null=True)),
                ('job_title', models.CharField(max_length=200)),
                ('job_description', models.TextField()),
                ('post_link', models.CharField(max_length=200)),
                ('published_date', models.CharField(max_length=200, null=True)),
                ('area', models.CharField(max_length=200, null=True)),
                ('jobstyle', models.CharField(max_length=200, null=True)),
                ('deadline', models.CharField(max_length=200, null=True)),
                ('salary', models.CharField(max_length=200, null=True)),
                ('education', models.CharField(max_length=200, null=True)),
                ('experience', models.CharField(max_length=200, null=True)),
                ('etc', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Job_JobKorea',
        ),
    ]
