# Generated by Django 3.0.6 on 2020-05-28 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200528_0253'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Job_Job_Korea',
            new_name='Job_Jobkorea',
        ),
    ]
